import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import EmbedSignIn from "~/components/EmbedSignIn";
import { api, type RouterOutputs } from "~/utils/api";
import Image from "next/image";
import dayjs from "dayjs";
import { useState } from "react";
import relativeTime from "dayjs/plugin/relativeTime";
import { LoadingPage } from "~/components/LoadingSpinner";
import toast from "react-hot-toast";

const Home: NextPage = () => {
  const { user, isLoaded: userLoaded } = useUser();

  api.posts.getAll.useQuery();

  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Twitter 2k23</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen min-h-screen flex-col items-center justify-center">
        <div className="h-full w-full border-x md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4 ">
            <div className="flex justify-center">
              <EmbedSignIn />
            </div>
            <div className="w-full">{!!user && <CreatePostWizard />}</div>
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
