/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */

import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import EmbedSignIn from "~/components/EmbedSignIn";
import { api, type RouterOutputs } from "~/utils/api";
import Image from "next/image";
import dayjs from "dayjs";
import { useState } from "react";
import relativeTime from "dayjs/plugin/relativeTime";
import { LoadingPage } from "~/components/LoadingSpinner";
import toast from "react-hot-toast";
import Link from "next/link";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const [inputText, setInputText] = useState<string>("");

  const { user } = useUser();

  const ctx = api.useContext();

  const { mutate, isLoading: isPosting } = api.posts.create.useMutation({
    onSuccess: () => {
      setInputText("");
      void ctx.posts.getAll.invalidate();
    },
    onError: () => {
      toast.error("Failed to post your message");
    },
  });

  if (!user) return null;

  return (
    <div className="flex w-full gap-3">
      <Image
        className="h-12 w-12 rounded-full"
        src={user.profileImageUrl}
        alt="Profile img"
        width={56}
        height={56}
      />
      <input
        type="text"
        placeholder="share your ideas 💭"
        className="grow bg-transparent outline-none"
        value={inputText}
        onChange={(e) => setInputText(e.target.value)}
        disabled={isPosting}
      />
      <button onClick={() => mutate({ content: inputText })}>Post</button>
    </div>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: { post: { post: PostWithUser } }) => {
  const { post, author } = props;

  return (
    <div className="flex gap-3 border-b border-slate-400 p-2" key={post.id}>
      <Image
        className="h-12 w-12 rounded-full"
        src={author.profileImageUrl}
        alt="Profile Img"
        width={56}
        height={56}
      />
      <div className="flex flex-col ">
        <div className="flex text-slate-300">
          <Link href={`/@${author.username}`}>
            <span className="gap-4">@{`${author.username}`}</span>&nbsp;·&nbsp;
          </Link>
          <Link href={`/post/${post.id}`}>
            <span>{dayjs(post.createdAt).fromNow()}</span>
          </Link>
        </div>
        <span className="text-md pt-1 text-slate-300">{post.content}</span>
      </div>
    </div>
  );
};

const Feed = () => {
  const { data, isLoading: postsLoading } = api.posts.getAll.useQuery();

  if (postsLoading) return <LoadingPage />;

  if (!data) return <div>Something went wrong</div>;

  return (
    <div className="flex flex-col">
      {data.map((fullPost, index) => (
        <PostView {...fullPost} key={`${fullPost.post.id}-${index}`} />
      ))}
    </div>
  );
};

const Home: NextPage = () => {
  const { user, isLoaded: userLoaded } = useUser();

  api.posts.getAll.useQuery();

  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Twitter 2k23</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen min-h-screen flex-col items-center justify-center">
        <div className="h-full w-full border-x md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4 ">
            <div className="flex justify-center">
              <EmbedSignIn />
            </div>
            <div className="w-full">{!!user && <CreatePostWizard />}</div>
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
